---
- name: Configure Windows Server
  hosts: windows
  gather_facts: no
  roles:
    - active_directory
    - CA
    - iis_web_srv

- name: Deploy Splunk Container
  hosts: localhost
  gather_facts: no
  roles:
    - splunk 