---
- name: Install smbclient
  apt:
    name: smbclient
    state: present
  when: ansible_os_family == "Debian"

- name: Create mount directory
  file:
    path: /mnt/win_iis_logs
    state: directory
  when: ansible_os_family == "Debian"

- name: Mount shared folder
  mount:
    path: /mnt/windows_iis_logs
    src: //192.168.2.230/LogFiles
    fstype: cifs
    opts: username=ubuntu,password=12345678@Rd
    state: mounted
  when: ansible_os_family == "Debian"