---
- name: Install Active Directory Domain Services
  ansible.windows.win_feature:
    name: AD-Domain-Services
    state: present
  notify: Reboot the server

- name: Create a new domain
  ansible.windows.win_domain:
    dns_domain_name: amar.local
    safe_mode_password: "Rd123456"
    domain_netbios_name: AMAR
    domain_mode: WinThreshold
    forest_mode: WinThreshold
    database_path: "C:\\Windows\\NTDS"
    sysvol_path: "C:\\Windows\\SYSVOL"
    create_dns_delegation: no
    domain_admin_user: "dadmin"
    domain_admin_password: "Rd123456"
  register: domain_result
  notify: Reboot the server
