---
- name: Install IIS Web-Server
  ansible.windows.win_feature:
    name: Web-Server,Web-Common-Http
    state: present
  register: iis_result
  notify: Reboot the server

- name: Share IIS log folder
  ansible.windows.win_share:
    name: LogFiles
    description: Shared IIS Logs
    path: C:\inetpub\logs\LogFiles
    list: yes
    full: Administrators

- name: Restart Service
  ansible.windows.win_service:
    name: LanmanServer
    state: restarted
    force_dependent_services: yes